### ISSUE TITLE
preloaders are bad

### ISSUE THREAD

**Issue by ciolt** [PoonsOfficial/PoonsOfficial.github.io#2]
https://github.com/PoonsOfficial/PoonsOfficial.github.io/blob/0ba78097a5791144a0492b3137d759676cd1b4d6/index.html#L208-L213

*This is the malignant code causing my endless frustration on this webspace.*

I tested the loading speed with and without the preloader, and the site takes significantly more time to fully appear with the preloader vs. without. I suggest simply removing this block of code and letting it be as-is.

**Comment by PoonsOfficial** [comment]
I see where you're coming from but the pre-loader was just an aesthetic element to the website. Removing it would be more efficient as you said. I might just do a JS timer that will have a pre-defined "loading" time. Overall, thanks for the **major** amounts fo testing you've done. <3
