### ISSUE TITLE
Is this a newsletter sign up box?

### ISSUE THREAD

**Issue by ciolt** [PoonsOfficial/PoonsOfficial.github.io#3]
What's this? 🤔

https://github.com/PoonsOfficial/PoonsOfficial.github.io/blob/0ba78097a5791144a0492b3137d759676cd1b4d6/index.html#L67-L95

**Comment by PoonsOfficial** [comment]
Yea, I was thinking about adding one but later scrapped the idea. I left it in the framework just in case I ever decide to add it back
¯\_(ツ)_/¯
